apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - serviceAccount.yaml

configurations:
  - servicemonitorMatchLabels.yaml

secretGenerator:
  - name: env
    envs:
      - app.env
