apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
  - ingress.yaml

replacements:
  # HPA setup
  - source:
      kind: Deployment
      fieldPath: metadata.name
    targets:
      - select:
          kind: HorizontalPodAutoscaler
          name: hpa
        fieldPaths:
          - spec.scaleTargetRef.name
  # Ingress setup
  - source:
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
          name: ingress
        fieldPaths:
          - spec.rules.*.http.paths.*.backend.service.name

secretGenerator:
  - name: env
    envs:
      - app.env
