nameReference:
  - kind: Deployment
    fieldSpecs:
      - kind: Rollout
        path: spec/workloadRef/name
  - kind: Rollout
    fieldSpecs:
      - kind: HorizontalPodAutoscaler
        path: spec/scaleTargetRef/name
  - kind: Service
    name: service
    fieldSpecs:
      - kind: Rollout
        path: spec/strategy/blueGreen/activeService
  - kind: Service
    name: service-preview
    fieldSpecs:
      - kind: Rollout
        path: spec/strategy/blueGreen/previewService
