apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  # Controlled by HPA
  replicas: 1
  selector:
    matchLabels: {}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 300s}
