################################################
# Standardized Service
################################################
apiVersion: v1
kind: Service
metadata:
  name: service-preview
spec:
  type: ClusterIP
  selector: {}
  ports:
    - port: 80
      targetPort: app
      protocol: TCP
