apiVersion: argoproj.io/v1alpha1
kind: Rollout
spec:
  template:
    spec:
        # Avoid pods to be deployed to the same node or availability zone
        topologySpreadConstraints:
          - labelSelector:
              matchLabels: {}
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
          - labelSelector:
              matchLabels: {}
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
