apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: ingress-internal.*
  patch: |-
    - op: replace
      path: /spec/ingressClassName
      value: nginx-internal-http
