apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Path to the main kustomization.yaml
resources:
- ../../base

patchesStrategicMerge:
- resources.yaml
- serviceAccountAnnotation.yaml

secretGenerator:
- name: env
  behavior: merge
  envs:
  - vault.env
