apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkpolicy-ingress-allow-internet-facing-nginx
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
      - podSelector:
          matchExpressions:
            - key: infra/app
              operator: In
              values:
              - ingress-nginx-internet-facing
            - key: infra/component
              operator: In
              values:
              - controller
      - namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values: [ingress-internet-facing]
    ports:
    - port: 80
      protocol: TCP
