apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/lokalise/kustomize-service-base/manifests/deployment
  - github.com/lokalise/kustomize-service-base/manifests/ingress

namePrefix: "example-"

images:
- name: base
  newName: ealen/echo-server
  newTag: latest

commonLabels:
  app: echo

namespace: lok

secretGenerator:
  - name: env
    behavior: create
    envs:
      - defaults.env
