apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # To change the job's command, create a patch in an overlay:
  # - patch: |-
  #   apiVersion: batch/v1
  #   kind: CronJob
  #   metadata:
  #     name: cronjob
  #   spec:
  #     schedule: "0 12 * * *"
  #     jobTemplate:
  #       spec:
  #         containers:
  #           - name: app
  #             command:
  #               - "npm"
  #               - "run"
  #               - "daily-cleanup"
  - cronjob.yaml

# To populate the secret associated with the Cronjob,
# use the following snippet in an overlay:
# secretGenerator:
# - behavior: merge
#   envs:
#   - vault.env
#   name: cronjob-env
secretGenerator:
- name: cronjob-env
  behavior: create
