on:
  push:
    branches:
      - main
    paths:
      - 'manifests/**'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mathieudutour/github-tag-action@v6.0
        name: Bump version and push tag
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
